// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BossList.proto

package com.wjl.serialize.protobuf;

public final class BossListProto {
  private BossListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BossListReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code BossListReq}
   */
  public static final class BossListReq extends
      com.google.protobuf.GeneratedMessage
      implements BossListReqOrBuilder {
    // Use BossListReq.newBuilder() to construct.
    private BossListReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BossListReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BossListReq defaultInstance;
    public static BossListReq getDefaultInstance() {
      return defaultInstance;
    }

    public BossListReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BossListReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjl.serialize.protobuf.BossListProto.internal_static_BossListReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjl.serialize.protobuf.BossListProto.internal_static_BossListReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjl.serialize.protobuf.BossListProto.BossListReq.class, com.wjl.serialize.protobuf.BossListProto.BossListReq.Builder.class);
    }

    public static com.google.protobuf.Parser<BossListReq> PARSER =
        new com.google.protobuf.AbstractParser<BossListReq>() {
      public BossListReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BossListReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BossListReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wjl.serialize.protobuf.BossListProto.BossListReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wjl.serialize.protobuf.BossListProto.BossListReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BossListReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wjl.serialize.protobuf.BossListProto.BossListReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjl.serialize.protobuf.BossListProto.internal_static_BossListReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjl.serialize.protobuf.BossListProto.internal_static_BossListReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjl.serialize.protobuf.BossListProto.BossListReq.class, com.wjl.serialize.protobuf.BossListProto.BossListReq.Builder.class);
      }

      // Construct using com.wjl.serialize.protobuf.BossListProto.BossListReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjl.serialize.protobuf.BossListProto.internal_static_BossListReq_descriptor;
      }

      public com.wjl.serialize.protobuf.BossListProto.BossListReq getDefaultInstanceForType() {
        return com.wjl.serialize.protobuf.BossListProto.BossListReq.getDefaultInstance();
      }

      public com.wjl.serialize.protobuf.BossListProto.BossListReq build() {
        com.wjl.serialize.protobuf.BossListProto.BossListReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjl.serialize.protobuf.BossListProto.BossListReq buildPartial() {
        com.wjl.serialize.protobuf.BossListProto.BossListReq result = new com.wjl.serialize.protobuf.BossListProto.BossListReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjl.serialize.protobuf.BossListProto.BossListReq) {
          return mergeFrom((com.wjl.serialize.protobuf.BossListProto.BossListReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjl.serialize.protobuf.BossListProto.BossListReq other) {
        if (other == com.wjl.serialize.protobuf.BossListProto.BossListReq.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjl.serialize.protobuf.BossListProto.BossListReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjl.serialize.protobuf.BossListProto.BossListReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BossListReq)
    }

    static {
      defaultInstance = new BossListReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BossListReq)
  }

  public interface BossOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required string title = 3;
    /**
     * <code>required string title = 3;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 3;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 3;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // required string email = 4;
    /**
     * <code>required string email = 4;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code Boss}
   */
  public static final class Boss extends
      com.google.protobuf.GeneratedMessage
      implements BossOrBuilder {
    // Use Boss.newBuilder() to construct.
    private Boss(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Boss(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Boss defaultInstance;
    public static Boss getDefaultInstance() {
      return defaultInstance;
    }

    public Boss getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Boss(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              title_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              email_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjl.serialize.protobuf.BossListProto.internal_static_Boss_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjl.serialize.protobuf.BossListProto.internal_static_Boss_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjl.serialize.protobuf.BossListProto.Boss.class, com.wjl.serialize.protobuf.BossListProto.Boss.Builder.class);
    }

    public static com.google.protobuf.Parser<Boss> PARSER =
        new com.google.protobuf.AbstractParser<Boss>() {
      public Boss parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Boss(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Boss> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string title = 3;
    public static final int TITLE_FIELD_NUMBER = 3;
    private java.lang.Object title_;
    /**
     * <code>required string title = 3;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string title = 3;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string email = 4;
    public static final int EMAIL_FIELD_NUMBER = 4;
    private java.lang.Object email_;
    /**
     * <code>required string email = 4;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      title_ = "";
      email_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEmailBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEmailBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wjl.serialize.protobuf.BossListProto.Boss parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjl.serialize.protobuf.BossListProto.Boss parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.Boss parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjl.serialize.protobuf.BossListProto.Boss parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.Boss parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wjl.serialize.protobuf.BossListProto.Boss parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.Boss parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wjl.serialize.protobuf.BossListProto.Boss parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.Boss parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wjl.serialize.protobuf.BossListProto.Boss parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wjl.serialize.protobuf.BossListProto.Boss prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Boss}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wjl.serialize.protobuf.BossListProto.BossOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjl.serialize.protobuf.BossListProto.internal_static_Boss_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjl.serialize.protobuf.BossListProto.internal_static_Boss_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjl.serialize.protobuf.BossListProto.Boss.class, com.wjl.serialize.protobuf.BossListProto.Boss.Builder.class);
      }

      // Construct using com.wjl.serialize.protobuf.BossListProto.Boss.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjl.serialize.protobuf.BossListProto.internal_static_Boss_descriptor;
      }

      public com.wjl.serialize.protobuf.BossListProto.Boss getDefaultInstanceForType() {
        return com.wjl.serialize.protobuf.BossListProto.Boss.getDefaultInstance();
      }

      public com.wjl.serialize.protobuf.BossListProto.Boss build() {
        com.wjl.serialize.protobuf.BossListProto.Boss result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjl.serialize.protobuf.BossListProto.Boss buildPartial() {
        com.wjl.serialize.protobuf.BossListProto.Boss result = new com.wjl.serialize.protobuf.BossListProto.Boss(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.email_ = email_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjl.serialize.protobuf.BossListProto.Boss) {
          return mergeFrom((com.wjl.serialize.protobuf.BossListProto.Boss)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjl.serialize.protobuf.BossListProto.Boss other) {
        if (other == com.wjl.serialize.protobuf.BossListProto.Boss.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000004;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000008;
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjl.serialize.protobuf.BossListProto.Boss parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjl.serialize.protobuf.BossListProto.Boss) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // required string title = 3;
      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 3;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string title = 3;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 3;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 3;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 3;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }

      // required string email = 4;
      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 4;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string email = 4;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 4;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000008);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Boss)
    }

    static {
      defaultInstance = new Boss(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Boss)
  }

  public interface BossListRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Boss bosses = 1;
    /**
     * <code>repeated .Boss bosses = 1;</code>
     */
    java.util.List<com.wjl.serialize.protobuf.BossListProto.Boss> 
        getBossesList();
    /**
     * <code>repeated .Boss bosses = 1;</code>
     */
    com.wjl.serialize.protobuf.BossListProto.Boss getBosses(int index);
    /**
     * <code>repeated .Boss bosses = 1;</code>
     */
    int getBossesCount();
    /**
     * <code>repeated .Boss bosses = 1;</code>
     */
    java.util.List<? extends com.wjl.serialize.protobuf.BossListProto.BossOrBuilder> 
        getBossesOrBuilderList();
    /**
     * <code>repeated .Boss bosses = 1;</code>
     */
    com.wjl.serialize.protobuf.BossListProto.BossOrBuilder getBossesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code BossListResp}
   */
  public static final class BossListResp extends
      com.google.protobuf.GeneratedMessage
      implements BossListRespOrBuilder {
    // Use BossListResp.newBuilder() to construct.
    private BossListResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BossListResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BossListResp defaultInstance;
    public static BossListResp getDefaultInstance() {
      return defaultInstance;
    }

    public BossListResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BossListResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                bosses_ = new java.util.ArrayList<com.wjl.serialize.protobuf.BossListProto.Boss>();
                mutable_bitField0_ |= 0x00000001;
              }
              bosses_.add(input.readMessage(com.wjl.serialize.protobuf.BossListProto.Boss.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          bosses_ = java.util.Collections.unmodifiableList(bosses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjl.serialize.protobuf.BossListProto.internal_static_BossListResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjl.serialize.protobuf.BossListProto.internal_static_BossListResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjl.serialize.protobuf.BossListProto.BossListResp.class, com.wjl.serialize.protobuf.BossListProto.BossListResp.Builder.class);
    }

    public static com.google.protobuf.Parser<BossListResp> PARSER =
        new com.google.protobuf.AbstractParser<BossListResp>() {
      public BossListResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BossListResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BossListResp> getParserForType() {
      return PARSER;
    }

    // repeated .Boss bosses = 1;
    public static final int BOSSES_FIELD_NUMBER = 1;
    private java.util.List<com.wjl.serialize.protobuf.BossListProto.Boss> bosses_;
    /**
     * <code>repeated .Boss bosses = 1;</code>
     */
    public java.util.List<com.wjl.serialize.protobuf.BossListProto.Boss> getBossesList() {
      return bosses_;
    }
    /**
     * <code>repeated .Boss bosses = 1;</code>
     */
    public java.util.List<? extends com.wjl.serialize.protobuf.BossListProto.BossOrBuilder> 
        getBossesOrBuilderList() {
      return bosses_;
    }
    /**
     * <code>repeated .Boss bosses = 1;</code>
     */
    public int getBossesCount() {
      return bosses_.size();
    }
    /**
     * <code>repeated .Boss bosses = 1;</code>
     */
    public com.wjl.serialize.protobuf.BossListProto.Boss getBosses(int index) {
      return bosses_.get(index);
    }
    /**
     * <code>repeated .Boss bosses = 1;</code>
     */
    public com.wjl.serialize.protobuf.BossListProto.BossOrBuilder getBossesOrBuilder(
        int index) {
      return bosses_.get(index);
    }

    private void initFields() {
      bosses_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getBossesCount(); i++) {
        if (!getBosses(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < bosses_.size(); i++) {
        output.writeMessage(1, bosses_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < bosses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bosses_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wjl.serialize.protobuf.BossListProto.BossListResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wjl.serialize.protobuf.BossListProto.BossListResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wjl.serialize.protobuf.BossListProto.BossListResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BossListResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wjl.serialize.protobuf.BossListProto.BossListRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjl.serialize.protobuf.BossListProto.internal_static_BossListResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjl.serialize.protobuf.BossListProto.internal_static_BossListResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjl.serialize.protobuf.BossListProto.BossListResp.class, com.wjl.serialize.protobuf.BossListProto.BossListResp.Builder.class);
      }

      // Construct using com.wjl.serialize.protobuf.BossListProto.BossListResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBossesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (bossesBuilder_ == null) {
          bosses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          bossesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjl.serialize.protobuf.BossListProto.internal_static_BossListResp_descriptor;
      }

      public com.wjl.serialize.protobuf.BossListProto.BossListResp getDefaultInstanceForType() {
        return com.wjl.serialize.protobuf.BossListProto.BossListResp.getDefaultInstance();
      }

      public com.wjl.serialize.protobuf.BossListProto.BossListResp build() {
        com.wjl.serialize.protobuf.BossListProto.BossListResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wjl.serialize.protobuf.BossListProto.BossListResp buildPartial() {
        com.wjl.serialize.protobuf.BossListProto.BossListResp result = new com.wjl.serialize.protobuf.BossListProto.BossListResp(this);
        int from_bitField0_ = bitField0_;
        if (bossesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            bosses_ = java.util.Collections.unmodifiableList(bosses_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.bosses_ = bosses_;
        } else {
          result.bosses_ = bossesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjl.serialize.protobuf.BossListProto.BossListResp) {
          return mergeFrom((com.wjl.serialize.protobuf.BossListProto.BossListResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjl.serialize.protobuf.BossListProto.BossListResp other) {
        if (other == com.wjl.serialize.protobuf.BossListProto.BossListResp.getDefaultInstance()) return this;
        if (bossesBuilder_ == null) {
          if (!other.bosses_.isEmpty()) {
            if (bosses_.isEmpty()) {
              bosses_ = other.bosses_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBossesIsMutable();
              bosses_.addAll(other.bosses_);
            }
            onChanged();
          }
        } else {
          if (!other.bosses_.isEmpty()) {
            if (bossesBuilder_.isEmpty()) {
              bossesBuilder_.dispose();
              bossesBuilder_ = null;
              bosses_ = other.bosses_;
              bitField0_ = (bitField0_ & ~0x00000001);
              bossesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBossesFieldBuilder() : null;
            } else {
              bossesBuilder_.addAllMessages(other.bosses_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getBossesCount(); i++) {
          if (!getBosses(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjl.serialize.protobuf.BossListProto.BossListResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjl.serialize.protobuf.BossListProto.BossListResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Boss bosses = 1;
      private java.util.List<com.wjl.serialize.protobuf.BossListProto.Boss> bosses_ =
        java.util.Collections.emptyList();
      private void ensureBossesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          bosses_ = new java.util.ArrayList<com.wjl.serialize.protobuf.BossListProto.Boss>(bosses_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.wjl.serialize.protobuf.BossListProto.Boss, com.wjl.serialize.protobuf.BossListProto.Boss.Builder, com.wjl.serialize.protobuf.BossListProto.BossOrBuilder> bossesBuilder_;

      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public java.util.List<com.wjl.serialize.protobuf.BossListProto.Boss> getBossesList() {
        if (bossesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bosses_);
        } else {
          return bossesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public int getBossesCount() {
        if (bossesBuilder_ == null) {
          return bosses_.size();
        } else {
          return bossesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public com.wjl.serialize.protobuf.BossListProto.Boss getBosses(int index) {
        if (bossesBuilder_ == null) {
          return bosses_.get(index);
        } else {
          return bossesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public Builder setBosses(
          int index, com.wjl.serialize.protobuf.BossListProto.Boss value) {
        if (bossesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBossesIsMutable();
          bosses_.set(index, value);
          onChanged();
        } else {
          bossesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public Builder setBosses(
          int index, com.wjl.serialize.protobuf.BossListProto.Boss.Builder builderForValue) {
        if (bossesBuilder_ == null) {
          ensureBossesIsMutable();
          bosses_.set(index, builderForValue.build());
          onChanged();
        } else {
          bossesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public Builder addBosses(com.wjl.serialize.protobuf.BossListProto.Boss value) {
        if (bossesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBossesIsMutable();
          bosses_.add(value);
          onChanged();
        } else {
          bossesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public Builder addBosses(
          int index, com.wjl.serialize.protobuf.BossListProto.Boss value) {
        if (bossesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBossesIsMutable();
          bosses_.add(index, value);
          onChanged();
        } else {
          bossesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public Builder addBosses(
          com.wjl.serialize.protobuf.BossListProto.Boss.Builder builderForValue) {
        if (bossesBuilder_ == null) {
          ensureBossesIsMutable();
          bosses_.add(builderForValue.build());
          onChanged();
        } else {
          bossesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public Builder addBosses(
          int index, com.wjl.serialize.protobuf.BossListProto.Boss.Builder builderForValue) {
        if (bossesBuilder_ == null) {
          ensureBossesIsMutable();
          bosses_.add(index, builderForValue.build());
          onChanged();
        } else {
          bossesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public Builder addAllBosses(
          java.lang.Iterable<? extends com.wjl.serialize.protobuf.BossListProto.Boss> values) {
        if (bossesBuilder_ == null) {
          ensureBossesIsMutable();
          super.addAll(values, bosses_);
          onChanged();
        } else {
          bossesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public Builder clearBosses() {
        if (bossesBuilder_ == null) {
          bosses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          bossesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public Builder removeBosses(int index) {
        if (bossesBuilder_ == null) {
          ensureBossesIsMutable();
          bosses_.remove(index);
          onChanged();
        } else {
          bossesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public com.wjl.serialize.protobuf.BossListProto.Boss.Builder getBossesBuilder(
          int index) {
        return getBossesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public com.wjl.serialize.protobuf.BossListProto.BossOrBuilder getBossesOrBuilder(
          int index) {
        if (bossesBuilder_ == null) {
          return bosses_.get(index);  } else {
          return bossesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public java.util.List<? extends com.wjl.serialize.protobuf.BossListProto.BossOrBuilder> 
           getBossesOrBuilderList() {
        if (bossesBuilder_ != null) {
          return bossesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bosses_);
        }
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public com.wjl.serialize.protobuf.BossListProto.Boss.Builder addBossesBuilder() {
        return getBossesFieldBuilder().addBuilder(
            com.wjl.serialize.protobuf.BossListProto.Boss.getDefaultInstance());
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public com.wjl.serialize.protobuf.BossListProto.Boss.Builder addBossesBuilder(
          int index) {
        return getBossesFieldBuilder().addBuilder(
            index, com.wjl.serialize.protobuf.BossListProto.Boss.getDefaultInstance());
      }
      /**
       * <code>repeated .Boss bosses = 1;</code>
       */
      public java.util.List<com.wjl.serialize.protobuf.BossListProto.Boss.Builder> 
           getBossesBuilderList() {
        return getBossesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.wjl.serialize.protobuf.BossListProto.Boss, com.wjl.serialize.protobuf.BossListProto.Boss.Builder, com.wjl.serialize.protobuf.BossListProto.BossOrBuilder> 
          getBossesFieldBuilder() {
        if (bossesBuilder_ == null) {
          bossesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.wjl.serialize.protobuf.BossListProto.Boss, com.wjl.serialize.protobuf.BossListProto.Boss.Builder, com.wjl.serialize.protobuf.BossListProto.BossOrBuilder>(
                  bosses_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          bosses_ = null;
        }
        return bossesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:BossListResp)
    }

    static {
      defaultInstance = new BossListResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BossListResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BossListReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BossListReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Boss_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Boss_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BossListResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BossListResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016BossList.proto\"\031\n\013BossListReq\022\n\n\002id\030\001 " +
      "\002(\005\">\n\004Boss\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\r\n" +
      "\005title\030\003 \002(\t\022\r\n\005email\030\004 \002(\t\"%\n\014BossListR" +
      "esp\022\025\n\006bosses\030\001 \003(\0132\005.BossB+\n\032com.wjl.se" +
      "rialize.protobufB\rBossListProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BossListReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BossListReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BossListReq_descriptor,
              new java.lang.String[] { "Id", });
          internal_static_Boss_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Boss_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Boss_descriptor,
              new java.lang.String[] { "Id", "Name", "Title", "Email", });
          internal_static_BossListResp_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_BossListResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BossListResp_descriptor,
              new java.lang.String[] { "Bosses", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
